"""Generate the appendix tables and listings from the evaluation sources.

Produces three groups of artifacts:

  1. thesis/tables/query_set_full.tex — the full 28-query set from
     configs/eval_queries.yaml as a longtable (Appendix C).
  2. thesis/tables/per_query_v4.tex — per-query RAGAS three-run means of
     the primary configuration V4 from the final_v1 artifacts
     (Appendix D).
  3. thesis/content/appendix/outputs/<id>_{v4,v0}.tex — complete answers
     of run r1 for the four scenario queries, V4 and the V0 contrast
     (Appendix E).

    .venv/bin/python scripts/appendix_to_tex.py
"""

from __future__ import annotations

import glob
import json
from pathlib import Path
from statistics import mean

import yaml

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "data" / "evaluation_results" / "setup_b"
TABLES = ROOT / "thesis" / "tables"
OUTPUTS = ROOT / "thesis" / "content" / "appendix" / "outputs"

TASK_LABELS = {
    "vulnerability_analysis": "Vulnerability analysis",
    "ioc_enrichment": "IOC enrichment",
    "ttp_correlation": "TTP correlation",
    "cross_source": "Cross-source comparison",
}

SCENARIO_IDS = ["vuln_001", "ioc_003", "ttp_005", "cross_003"]

# Listings are ASCII-normalized: the generator maps the few non-ASCII
# characters the pipeline emits so pdflatex verbatim can render them.
CHAR_MAP = {"\u2014": "--", "\u2013": "-", "\u00b7": "-", "\u2019": "'",
            "\u201c": '"', "\u201d": '"', "\u2192": "->"}


def tex_escape(text: str) -> str:
    for char, repl in {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%",
                       "$": r"\$", "#": r"\#", "_": r"\_", "{": r"\{",
                       "}": r"\}", "~": r"\textasciitilde{}",
                       "^": r"\textasciicircum{}"}.items():
        text = text.replace(char, repl)
    return text


def ascii_normalize(text: str) -> str:
    for char, repl in CHAR_MAP.items():
        text = text.replace(char, repl)
    return text


def write_query_table() -> None:
    queries = yaml.safe_load((ROOT / "configs" / "eval_queries.yaml").read_text())["queries"]
    rows = []
    for q in queries:
        rows.append(
            f"        \\texttt{{{tex_escape(q['id'])}}} & "
            f"{TASK_LABELS[q['task_type']]} & {q['difficulty']} & "
            f"{tex_escape(q['question'])} \\\\"
        )
    body = "\n".join(rows)
    (TABLES / "query_set_full.tex").write_text(
        "% Auto-generated by scripts/appendix_to_tex.py from\n"
        "% configs/eval_queries.yaml --- do not edit by hand.\n"
        "\\begin{longtable}{lllp{0.47\\textwidth}}\n"
        "    \\toprule\n"
        "    \\textbf{ID} & \\textbf{Task type} & \\textbf{Difficulty} &"
        " \\textbf{Query} \\\\\n"
        "    \\midrule\n"
        "    \\endfirsthead\n"
        "    \\toprule\n"
        "    \\textbf{ID} & \\textbf{Task type} & \\textbf{Difficulty} &"
        " \\textbf{Query} \\\\\n"
        "    \\midrule\n"
        "    \\endhead\n"
        "    \\midrule\n"
        "    \\multicolumn{4}{r@{}}{\\footnotesize\\itshape continued on"
        " next page} \\\\\n"
        "    \\endfoot\n"
        "    \\bottomrule\n"
        "    \\caption{Complete evaluation query set (28 queries)}\n"
        "    \\label{tab:query-set-full}\n"
        "    \\endlastfoot\n"
        f"{body}\n"
        "\\end{longtable}\n"
    )
    print(f"wrote {TABLES / 'query_set_full.tex'} ({len(rows)} queries)")


def write_per_query_table() -> None:
    runs = [json.load(open(p)) for p in sorted(
        glob.glob(str(RESULTS / "ragas_hybrid_templated_final_v1_r*.json")))]
    assert len(runs) == 3, "expected three final_v1 runs"
    metrics = ["faithfulness", "answer_relevancy", "answer_correctness",
               "context_precision", "context_recall"]
    per_query: dict[str, list[dict]] = {}
    order: list[str] = []
    for run in runs:
        for s in run["per_sample"]:
            if s["id"] not in per_query:
                order.append(s["id"])
            per_query.setdefault(s["id"], []).append(s["ragas_metrics"])
    rows = []
    for qid in order:
        cells = []
        for metric in metrics:
            vals = [m[metric] for m in per_query[qid]
                    if m.get(metric) is not None]
            cells.append(f"{mean(vals):.2f}" if vals else "---")
        rows.append(f"        \\texttt{{{tex_escape(qid)}}} & "
                    + " & ".join(cells) + " \\\\")
    body = "\n".join(rows)
    (TABLES / "per_query_v4.tex").write_text(
        "% Auto-generated by scripts/appendix_to_tex.py from the\n"
        "% ragas_hybrid_templated_final_v1_r1..r3 artifacts --- do not"
        " edit by hand.\n"
        "\\begin{longtable}{lccccc}\n"
        "    \\toprule\n"
        "    \\textbf{ID} & \\textbf{Faith.} & \\textbf{Ans. rel.} &"
        " \\textbf{Ans. corr.} & \\textbf{Ctx. prec.} &"
        " \\textbf{Ctx. rec.} \\\\\n"
        "    \\midrule\n"
        "    \\endfirsthead\n"
        "    \\toprule\n"
        "    \\textbf{ID} & \\textbf{Faith.} & \\textbf{Ans. rel.} &"
        " \\textbf{Ans. corr.} & \\textbf{Ctx. prec.} &"
        " \\textbf{Ctx. rec.} \\\\\n"
        "    \\midrule\n"
        "    \\endhead\n"
        "    \\midrule\n"
        "    \\multicolumn{6}{r@{}}{\\footnotesize\\itshape continued on"
        " next page} \\\\\n"
        "    \\endfoot\n"
        "    \\bottomrule\n"
        "    \\caption{Per-query RAGAS scores of the primary"
        " configuration V4 (three-run means; --- where the judge"
        " returned no score)}\n"
        "    \\label{tab:per-query-v4}\n"
        "    \\endlastfoot\n"
        f"{body}\n"
        "\\end{longtable}\n"
    )
    print(f"wrote {TABLES / 'per_query_v4.tex'} ({len(rows)} queries)")


def write_output_listings() -> None:
    OUTPUTS.mkdir(exist_ok=True)
    sources = {
        "v4": glob.glob(str(RESULTS / "ragas_hybrid_templated_final_v1_r1_*.json"))[0],
        "v0": glob.glob(str(RESULTS / "ragas_baseline_final_v1_r1_*.json"))[0],
    }
    for kind, path in sources.items():
        data = json.load(open(path))
        samples = {s["id"]: s for s in data["per_sample"]}
        for qid in SCENARIO_IDS:
            answer = ascii_normalize(samples[qid]["answer"]).strip()
            dst = OUTPUTS / f"{qid}_{kind}.tex"
            dst.write_text(
                "% Auto-generated by scripts/appendix_to_tex.py from\n"
                f"% {Path(path).name} --- do not edit by hand.\n"
                "\\begin{lstlisting}[style=appendixoutput]\n"
                f"{answer}\n"
                "\\end{lstlisting}\n"
            )
    print(f"wrote {2 * len(SCENARIO_IDS)} listings to {OUTPUTS}")


if __name__ == "__main__":
    write_query_table()
    write_per_query_table()
    write_output_listings()
