"""Render the captured MCP demo transcript as a standalone LaTeX figure.

Reads docs/architecture/mcp_transcript.txt (captured via `make mcp-demo`)
and writes docs/architecture/mcp_transcript.tex, a standalone document
styled like the thesis response boxes. Compile and export with:

    python scripts/mcp_transcript_to_tex.py
    pdflatex -output-directory=/tmp docs/architecture/mcp_transcript.tex
    cp /tmp/mcp_transcript.pdf thesis/images/
"""

from __future__ import annotations

import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "docs" / "architecture" / "mcp_transcript.txt"
DST = ROOT / "docs" / "architecture" / "mcp_transcript.tex"

WRAP = 88  # characters per line at \small monospace on 15 cm

# Verbatim body uses fancyvrb commandchars, so \ { } are the only
# escapes; non-ASCII output characters map to LaTeX commands.
CHAR_MAP = {
    "\u2014": r"\textemdash{}",  # em dash in headings/footer
    "\u00b7": r"\textperiodcentered{}",  # separator in footer line
}


def wrap_line(line: str) -> list[str]:
    if len(line) <= WRAP:
        return [line]
    indent = " " * (len(line) - len(line.lstrip(" -")) + 2)
    return textwrap.wrap(
        line,
        width=WRAP,
        subsequent_indent=indent,
        break_long_words=True,
        break_on_hyphens=False,
    )


def main() -> None:
    lines: list[str] = []
    for raw in SRC.read_text().splitlines():
        for line in wrap_line(raw):
            for char, repl in CHAR_MAP.items():
                line = line.replace(char, repl)
            lines.append(line)
    body = "\n".join(lines)

    DST.write_text(
        "% Auto-generated by scripts/mcp_transcript_to_tex.py --- do not edit.\n"
        "% Source transcript: docs/architecture/mcp_transcript.txt\n"
        "\\documentclass[border=2pt]{standalone}\n"
        "\\usepackage[T1]{fontenc}\n"
        "\\usepackage[most]{tcolorbox}\n"
        "\\usepackage{fancyvrb}\n"
        "\\begin{document}\n"
        "\\begin{tcolorbox}[sharp corners, colback=gray!2, colframe=black!60,\n"
        "                  boxrule=0.5pt, width=15cm,\n"
        "                  left=2mm, right=2mm, top=1.5mm, bottom=1.5mm]\n"
        "\\begin{Verbatim}[fontsize=\\small, commandchars=\\\\\\{\\}]\n"
        f"{body}\n"
        "\\end{Verbatim}\n"
        "\\end{tcolorbox}\n"
        "\\end{document}\n"
    )
    print(f"wrote {DST} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
